.openpublishing.publish.config.json, docs/docfx.json
enable edit and feedback buttons
=> [config] enable public contributions

docs/Xamarin.Forms/SearchBar.xml
Added spaces at line 54. Fix for display glitch.
=> Fixes code display issue

docs/Xamarin.Forms/ReturnType.xml
Change the description for the Send return type to say send button rather than search
=> Change Send ReturnType Description

docs/Xamarin.Forms/Grid.xml
Other properties with defaults should likewise be specified.
=> Specify Grid spacing default

docs/Xamarin.Forms/GridLength.xml
=> Fix typo in GridLength Doc

docs/Xamarin.Forms/BindableObject.xml
Missing the word _in_: "_Returns the value that is contained **in** the BindableProperty."_
=> Missing words added

docs/Xamarin.Forms/Page.xml
Just two small typo fixes, removed an extra space and an extra letter.
=> Typo fixes

docs/Xamarin.Forms/NavigationPage.xml, docs/Xamarin.Forms/Shell.xml, docs/ns-Xamarin.Forms.xml
Still leaves 1 warning for nonexistent img. Tracking that down separately.
=> OPS Warnings

docs/Xamarin.Forms/ActivityIndicator.xml
Fixes https://github.com/xamarin/Xamarin.Forms-api-docs/issues/91
=> Changed bindable property boilerplate on IsRunningProperty

docs/Xamarin.Forms.Xaml/IMarkupExtension.xml
Fixed the unnecessary (broken) smaller-than and greater-than signs within a CDATA element.
=> HTML entities inside CDATA element

docs/Xamarin.Forms/KeyboardFlags.xml
Changed "Enumberates" to "Enumerates".
=> Fix spelling error

docs/Xamarin.Forms/ContentView.xml
Changed `fo` to `of`
Fixes #108
=> Fixes typo

docs/Xamarin.Forms/ContentPropertyAttribute.xml
Fixes two closing tags using the wrong slash.
=> Small fix for closing tags

docs/Xamarin.Forms/Layout.xml
While diving in the docs I noticed this typo, thought I'd fix it :)
=> Small typo in Layout.CascadeInputTransparent

docs/Xamarin.Forms/Picker.xml
Corrected Fuchsia mistyped at Fucshia
=> Update XFPicker typo

docs/Xamarin.Forms/VisualElement.xml
=> Fix typo on VisualElement

docs/Xamarin.Forms/FlexLayout.xml
=> Fix typo on FlexLayout

docs/Xamarin.Forms/DataTemplateSelector.xml
=> Fix typo on DatatemplateSelector page

docs/Xamarin.Forms/ColorTypeConverter.xml
=> Update example to use `ConvertFromInvariantString`

docs/Xamarin.Forms/RelativeLayout.xml
=> Fix link to FormsGallery sample

docs/Xamarin.Forms/VisualElement.xml
Added it to the summary element.  Fixes #219
=> Make rotation unit more clear

docs/Xamarin.Forms/FlyoutItem.xml
=> Fixed wrong description in Xamarin.Forms Flyout items docs

docs/Xamarin.Forms/BindableProperty.xml
=> Fixed wrong DataBinding blog article link

docs/Xamarin.Forms/StackLayout.xml
=> Fixed wrong FormsGallery sample link in StackLayout docs

docs/Xamarin.Forms.PlatformConfiguration.iOSSpecific/StatusBarHiddenMode.xml
=> Fixed wrong StatusBarHiddenMode enum description

docs/Xamarin.Forms/BindableObjectExtensions.xml
=> Improve the example of SetBinding

docs/Xamarin.Forms/Button.xml
=> Add better summaries to Button BindableProperties

docs/Xamarin.Forms.Xaml/ReferenceExtension.xml
=> Improve some docs for ReferenceExtension

docs/Xamarin.Forms/MasterDetailPage.xml
Fix typo "Fucshia" -> "Fuchsia"
(partially) fixes #100
=> Fix typo "Fucshia" -> "Fuchsia"

docs/Xamarin.Forms/ContentPage.xml
and Add Link for FormsGallery sample
fixes #157
=> Fix link for Sample Apps

docs/Xamarin.Forms.Xaml/ReferenceExtension.xml
Reverts xamarin/Xamarin.Forms-api-docs#250
=> Revert "Improve some docs for ReferenceExtension"

docs/Xamarin.Forms/Label.xml
=> Add description for TextType

docs/Xamarin.Forms/Color.xml
=> Update Transparent color value

docs/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/VisualElement.xml
SetElevation and SetIsLegacyColorMode had their descriptions/parameters swapped.
Fixes #115
=> Fix swapped docs information

docs/Xamarin.Forms/NavigationPage.xml
clarify PushAsync() docs and remove modal implications
fixes #88
=> Fix NavigationPage.xml

docs/Xamarin.Forms/MenuItem.xml
=> Add example of MenuItem IsDestructive

docs/ns-Xamarin.Forms.xml
=> [BrokenLinksH2] Fix path in link

docs/docfx.json
Enable build config to generate canonical URL with moniker
=> [SEO][Rollout Monikered Canonical]Add URL moniker

docs/Xamarin.Forms/Grid+IGridList`1.xml
There's no such thing as a HeightSpan.
=> Fix description of Add method
